version: '4'
services:
  mysql:
    image: mysql:8.0.0
    container_name: mysql-docker
    environment:
      MYSQL_ROOT_PASSWORD: kumar
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
